language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: WC0htt6WsS+qFM9EMp+UR5Xx3w88c8CDus/iBUy/ECOLNVrPvXyd7qlBuKtMEjTKUp3eXuFcuMPWmiFgwcNOQnHeV8br6Cjnx5+vtE1tFTibpf1CSJI/C9eMB2qCJZ8UDU1KPQbtJIIuO+Krasn+278Wf1K6QSkoTMQhirafU/WF80eyma5bn4mystiXiMDc/QFa1MZEqvs+3iNtX7/l20tOQAWCbO9fnZyTHMD8bj2pR2hgTHCera9bPodLOtljNr+svb/addJXD6N5YuLAvsfGecvQTr2q9LVQ91V9FK0rtINhfmFlwVtuVqU4LP9tj2FIQ8omhOSlnwwlvVQHLjtHaEwZRVY/BgEVrxm/u57XOMjuS6LPUdR+fUNvWhCiaK8vVxfceJ55qX40vaNP083aqz2bkx08WfAgzsL6dODIi1tgLJbrsfnX+tQ990z4vI5UFvJ491sDyWe14gkLECJmbnxP4Ojjn8LdLLJjWf6/PecOAXgW/cUnKTZjI7CjIjzxyugp4JBXYF57WFgLuZrZcVMQsfRFGuZtLHA/84EgZ3ozgF0MeWsBVUxtU98EDrSIYZlDY2glaiFrogCD90VCGjwtGQ7wv0Y7ISc2OY4fybAwhYwWDQw78XQS0FU6FY3pzt8niDo01mbz79ac+ein9Rf6xQNZV5sx6Jf4rZY=
  - secure: UasKd5jsaXmUfUOmeJiQPJNqMsnRkUOAJT6+UP31GPwm1T5Gs2L/WaV6Uy1s+PZDnEzJwR4n3qqM4y3PLgCjRc1Bq+Rd9mkq2PxF8VsHKpPqvP1avU7IcLo2i8Q0r0cgIx1mROufG7geWRcBNQtLj+JlbQWePm2NwfeS0SCULl0J7SFTXylv9+Ff+VLdk+k8ejeQdGIZoWunUw5W/C+ZYvPwDsoZ+YMc6iADeKxc8zCCM6aUY4avmZGTB2AzuzXgZjr/zTyNHVS/MM0iqEXEveeVvOImWg4/2Ns/IepDznO1fp+6zzxPVLmxE18iXvOe66hqpDOBdZkjwjYgPVCidScwtV+N/sgXlZOTlDqLQycPTjLlwBzXw6BuQhTHEMTlFxNktGO2ei20RkBVOdVgEKbBqJ1L6UlqQZ0+nmq2Ix0QZLyoWBTsS1lOGzYJcm1VkUKTc2jIuTJOe13C8QYWOkcKH1bmG5k3lzrb0MHYWx4Z7Dfh+az01G42w34lqHUUJvU8MUtimrObjza8q0lvAhoECuwtBuIYiY9GbUx+8e0WalmmE80pUehl1LkAVR1UorNWp5wlelddaj/M5D1jyp+kVmN7hwxcjTU7XxtHLsVVD2eS8DaHLsPcw8SCGlEg8cmGotW4IFlc9H0DQzT6Ayr5HPttxUAQu9AeUWNI5FE=
